version: "3.3"
services:
    fpm:
        build: .
        container_name: pf-fpm
        depends_on:
            - mariadb
        volumes:
            - pf-code:/opt/pathfinder
            - ./cfg/environment.ini:/opt/pathfinder/conf/environment.ini:ro
        networks:
            - pf-network

    mariadb:
        image: mariadb:10
        container_name: pf-mariadb
        environment:
            MYSQL_RANDOM_ROOT_PASSWORD: "yes"
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        volumes:
          - ./sql:/docker-entrypoint-initdb.d:ro
          - pf-mariadb:/var/lib/mysql
          - ./cfg/mariadb-pathfinder.cnf:/etc/mysql/conf.d/pf.cnf:ro
        networks:
            - pf-network

    nginx:
        image: nginx:alpine
        container_name: pf-nginx
        depends_on:
            - fpm 
        volumes:
            - pf-code:/opt/pathfinder
            - ./cfg/nginx.conf:/etc/nginx/nginx.conf
            - ./.htpasswd:/opt/pathfinder/.setup_pass
        ports:
            - "127.0.0.1:${NGINX_PORT}:80"
            - "127.0.0.1:5555:5555"
        networks:
            - pf-network

volumes:
    pf-code:
    pf-mariadb:

networks:
    pf-network: